version: '3'

services:
  wikibase:
    image: "${WIKIBASE_BUNDLE_IMAGE_NAME}"
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "${WIKIBASE_PORT}:80"
    volumes:
      - ./extra-install.sh:/extra-install.sh
      - ./LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php

    networks:
      default:
        aliases:
         - host.docker.internal
    environment:
      - DB_SERVER=mysql:3306
      - MW_ADMIN_NAME=${MW_ADMIN_NAME}
      - MW_ADMIN_PASS=${MW_ADMIN_PASS}
      - MW_ADMIN_EMAIL=${MW_ADMIN_EMAIL}
      - MW_WG_SECRET_KEY=${MW_SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - WIKIBASE_HOST
      - WIKIBASE_PINGBACK
  mysql:
    image: "${MYSQL_IMAGE_NAME}"
    restart: unless-stopped
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
        aliases:
         - host.docker.internal

volumes:
  LocalSettings:
  mediawiki-mysql-data:
